### ISSUE TITLE
No such file or directory: '/usr/local/share/icebox/timings_lp384.txt'

### ISSUE THREAD

**Issue by jiapei100** [YosysHQ/nextpnr#1256]
Trying to build **nextpnr** under **Ubuntu 22.04.3**. 
Got the following **ERROR**. 
Where can I find **icebox** ?

```console
[  2%] Generating qrc_qtpropertybrowser.cpp
cd ....../nextpnr/build/generated/3rdparty/QtPropertyBrowser/src && /opt/qt/5/bin/rcc --name qtpropertybrowser --output ....../nextpnr/build/generated/3rdparty/QtPropertyBrowser/src/qrc_qtpropertybrowser.cpp ....../nextpnr/3rdparty/QtPropertyBrowser/src/qtpropertybrowser.qrc
cd ....../nextpnr/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" ....../nextpnr ....../nextpnr/3rdparty/QtPropertyBrowser/src ....../nextpnr/build ....../nextpnr/build/generated/3rdparty/QtPropertyBrowser/src ....../nextpnr/build/generated/3rdparty/QtPropertyBrowser/src/CMakeFiles/QtPropertyBrowser.dir/DependInfo.cmake "--color="
Traceback (most recent call last):
  File "....../nextpnr/ice40/chipdb.py", line 254, in <module>
    slow_timings = read_timings(args.slow)
  File "....../nextpnr/ice40/chipdb.py", line 233, in read_timings
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/icebox/timings_lp384.txt'
make[2]: Leaving directory '....../nextpnr/build'
```

**Comment by jiapei100** [comment]
My god... must be [https://github.com/YosysHQ/icestorm/tree/master/icebox](https://github.com/YosysHQ/icestorm/tree/master/icebox)
