### ISSUE TITLE
Assigning to cell.bel from Python causes crash (generic arch)

### ISSUE THREAD

**Issue by vmedea** [YosysHQ/nextpnr#522]
I tried adding the following to `generic/examples/simple_timing.py` to constrain the I/O positions:
```python
# apply IO constraints
io_constraints = {
    'leds[0]$iob': 'X1Y0_IO0',
    'leds[1]$iob': 'X2Y0_IO0',
    'leds[2]$iob': 'X3Y0_IO0',
    'leds[3]$iob': 'X4Y0_IO0',
    'leds[4]$iob': 'X5Y0_IO0',
    'leds[5]$iob': 'X6Y0_IO0',
    'leds[6]$iob': 'X7Y0_IO0',
    'leds[7]$iob': 'X8Y0_IO0',
    'clk$iob': 'X9Y0_IO0',
    'rst$iob': 'X10Y0_IO0',
}

for cname, cell in ctx.cells:
    if cell.type != "GENERIC_IOB":
        continue
    print('Assigning', cname, 'to', io_constraints[cname])
    # crashes:
    cell.bel = io_constraints[cname]
    # works:
    #cell.setAttr('BEL', io_constraints[cname])
```
Assigning to `.bel` directly causes a crash—not immediately, but later during placement, with this traceback
```
$ gdb -args nextpnr-generic  --pre-pack simple.py --pre-place simple_timing.py --json blinky.json --post-route bitstream.py --write pnrblinky.json
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Reading symbols from nextpnr-generic...run
done.
(gdb) run
Starting program: /opt/yosys/bin/nextpnr-generic --pre-pack simple.py --pre-place simple_timing.py --json blinky.json --post-route bitstream.py --write pnrblinky.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".


Info: Packing constants..
Info: Packing IOs..
Info: Packing LUT-FFs..
Info: Packing non-LUT FFs..
Info: Checksum: 0xbfbc1d15

Info: Annotating ports with timing budgets for target frequency 12.00 MHz
Info: Checksum: 0xbfbc1d15

Info: Device utilisation:
Info:            GENERIC_IOB:    10/   84    11%
Info:          GENERIC_SLICE:    14/  800     1%

Assigning leds[2]$iob to X3Y0_IO0
Assigning leds[0]$iob to X1Y0_IO0
Assigning leds[6]$iob to X7Y0_IO0
Assigning leds[4]$iob to X5Y0_IO0
Assigning leds[7]$iob to X8Y0_IO0
Assigning clk$iob to X9Y0_IO0
Assigning leds[5]$iob to X6Y0_IO0
Assigning leds[3]$iob to X4Y0_IO0
Assigning rst$iob to X10Y0_IO0
Assigning leds[1]$iob to X2Y0_IO0
Info: Placed 0 cells based on constraints.
Info: Creating initial analytic placement for 12 cells, random placement wirelen = 207.
[New Thread 0x7fb625f1d0 (LWP 7062)]
Info:     at initial placer iter 0, wirelen = 27
[New Thread 0x7fb625f1d0 (LWP 7063)]
[Thread 0x7fb625f1d0 (LWP 7062) exited]
Info:     at initial placer iter 1, wirelen = 27
[New Thread 0x7fb625f1d0 (LWP 7064)]
[Thread 0x7fb625f1d0 (LWP 7063) exited]
Info:     at initial placer iter 2, wirelen = 27
[New Thread 0x7fb625f1d0 (LWP 7065)]
[Thread 0x7fb625f1d0 (LWP 7064) exited]
Info:     at initial placer iter 3, wirelen = 27
Info: Running main analytical placer.
[Thread 0x7fb625f1d0 (LWP 7065) exited]
Info:     at iteration #1, type GENERIC_SLICE: wirelen solved = 27, spread = 33, legal = 57; time = 0.00s
Info:     at iteration #2, type GENERIC_SLICE: wirelen solved = 27, spread = 34, legal = 66; time = 0.00s
Info:     at iteration #3, type GENERIC_SLICE: wirelen solved = 28, spread = 34, legal = 59; time = 0.00s
Info:     at iteration #4, type GENERIC_SLICE: wirelen solved = 29, spread = 34, legal = 55; time = 0.00s
Info:     at iteration #5, type GENERIC_SLICE: wirelen solved = 29, spread = 34, legal = 53; time = 0.00s
Info:     at iteration #6, type GENERIC_SLICE: wirelen solved = 27, spread = 34, legal = 55; time = 0.00s
Info:     at iteration #7, type GENERIC_SLICE: wirelen solved = 31, spread = 35, legal = 60; time = 0.00s
Info:     at iteration #8, type GENERIC_SLICE: wirelen solved = 32, spread = 40, legal = 66; time = 0.00s
Info:     at iteration #9, type GENERIC_SLICE: wirelen solved = 32, spread = 40, legal = 61; time = 0.00s
Info:     at iteration #10, type GENERIC_SLICE: wirelen solved = 32, spread = 39, legal = 61; time = 0.00s

Thread 1 "nextpnr-generic" received signal SIGSEGV, Segmentation fault.
0x000000555566460c in nextpnr_generic::Arch::unbindBel (this=0x55557326f0, bel=...) at /home/user/projects/fpga/ice/nextpnr/generic/arch.cc:302
302         bels.at(bel).bound_cell->bel = BelId();
(gdb) bt
#0  0x000000555566460c in nextpnr_generic::Arch::unbindBel (this=0x55557326f0, bel=...) at /home/user/projects/fpga/ice/nextpnr/generic/arch.cc:302
#1  0x00000055555d77d8 in nextpnr_generic::HeAPPlacer::place (this=this@entry=0x7fffffe400) at /home/user/projects/fpga/ice/nextpnr/common/placer_heap.cc:283
#2  0x00000055555c1f40 in nextpnr_generic::placer_heap (ctx=ctx@entry=0x55557326f0, cfg=...) at /home/user/projects/fpga/ice/nextpnr/common/placer_heap.cc:1726
#3  0x0000005555664230 in nextpnr_generic::Arch::place (this=0x55557326f0) at /home/user/projects/fpga/ice/nextpnr/generic/arch.cc:548
#4  0x0000005555583b68 in nextpnr_generic::CommandHandler::executeMain (this=this@entry=0x7fffffec90, ctx=std::unique_ptr<nextpnr_generic::Context> = {...}) at /home/user/projects/fpga/ice/nextpnr/common/command.cc:350
#5  0x0000005555585750 in nextpnr_generic::CommandHandler::exec (this=0x7fffffec90) at /home/user/projects/fpga/ice/nextpnr/common/command.cc:422
#6  0x0000005555579fc8 in main (argc=<optimized out>, argv=<optimized out>) at /home/user/projects/fpga/ice/nextpnr/generic/main.cc:72
(gdb)
```
The `cell.setAttr` works, and probably is the right way to do this, it's mostly that the error message could be better.

commit: 1afa494e69e3c8af3dd5d1685b9cd2b1d3bea4d0

**Comment by daveshah1** [comment]
Thanks for reporting - as it stands setting the BEL attribute as you've figured is indeed the best approach but it shouldn't crash in this way.
