### ISSUE TITLE
Failed to compile: GW1NS-4.pickle wasn't found

### ISSUE THREAD

**Issue by tuabu** [YosysHQ/nextpnr#891]
I'm running on arch and copied repo and have gone through manual install because the package from the aur failed everytime.
Now I was pretty convinced that it will work because the compile was pretty done far @ 85%.
In case I had already reinstalled apycula but since there is no GW1NS-4.pickle file.
Here the log:
Consolidate compiler generated dependencies of target gui_gowin
[ 85%] Built target gui_gowin
[ 85%] Generating chipdb/chipdb-GW1NS-4.bba
Traceback (most recent call last):
  File "/usr/bin/gowin_bba", line 33, in <module>
    sys.exit(load_entry_point('Apycula==0.2a1', 'console_scripts', 'gowin_bba')())
  File "/usr/lib/python3.10/site-packages/apycula/gowin_bba.py", line 226, in main
    with importlib.resources.open_binary("apycula", f"{args.device}.pickle") as f:
  File "/usr/lib/python3.10/importlib/resources.py", line 46, in open_binary
    return reader.open_resource(resource)
  File "/usr/lib/python3.10/importlib/abc.py", line 433, in open_resource
    return self.files().joinpath(resource).open('rb')
  File "/usr/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.10/site-packages/apycula/GW1NS-4.pickle'
make[2]: *** [gowin/CMakeFiles/chipdb-gowin-bbas.dir/build.make:106: gowin/chipdb/chipdb-GW1NS-4.bba] Error 1
make[1]: *** [CMakeFiles/Makefile2:1340: gowin/CMakeFiles/chipdb-gowin-bbas.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Hope you can help and stay healthy.

**Comment by tuabu** [comment]
So the compiling from source works perfectly fine.
It is just the package but that's here not the target.
Sorry for a waste of time.
Thank you for this great tool! keep on.
