### ISSUE TITLE
Boost exception on running nextpnr-gowin

### ISSUE THREAD

**Issue by ollelogdahl** [YosysHQ/nextpnr#946]
I build the package using the instructions:
```
cmake -DARCH="gowin"
make
sudo make install
```

When running `nextpnr-gowin` with any flags or none, i get:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_any_cast>'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)
```

Examining the gdb stacktrace:
```
#0  0x00007ffff623134c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007ffff61e44b8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff61ce534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff654a7ee in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff6556c4c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff6556cb9 in std::terminate () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff6556f5e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x555555ed53e8 <typeinfo for boost::wrapexcept<boost::bad_any_cast>>,
    dest=0x5555557524a0 <boost::wrapexcept<boost::bad_any_cast>::~wrapexcept()>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#7  0x00005555556d01ef in boost::throw_exception<boost::bad_any_cast>(boost::bad_any_cast const&) [clone .constprop.0] (e=...)
    at /usr/include/boost/throw_exception.hpp:162
#8  0x000055555569f363 in boost::any_cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (operand=...)
    at /usr/include/boost/any.hpp:274
#9  0x000055555586acd3 in boost::any_cast<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (operand=..., operand=...)
    at /usr/include/boost/any.hpp:297
#10 boost::program_options::variable_value::as<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=<optimized out>,
    this=<optimized out>) at /usr/include/boost/program_options/variables_map.hpp:69
#11 GowinCommandHandler::createContext (this=0x7fffffffdb30, values=...) at /home/olle/compile/nextpnr/gowin/main.cc:60
#12 0x000055555575806d in nextpnr_gowin::CommandHandler::exec (this=0x7fffffffdb30) at /home/olle/compile/nextpnr/common/command.cc:510
#13 0x00005555556d2ea5 in main (argc=<optimized out>, argv=<optimized out>) at /home/olle/compile/nextpnr/gowin/main.cc:94
```

I didn't encounter the same problem when running `nextpnr-generic`. I would issue this to apicula but not sure where this lies. Any pointers whould gladly help.

SYSTEM: Arch linux
Boost version: 1.78.0-1 (both lib and boost)

**Comment by yrabbit** [comment]
Well, the situation may change for the better:)

https://github.com/YosysHQ/nextpnr/pull/950
